config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'blog#index'
  resources :blog
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :set_content, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @blog = Content.includes(:user).order("created_at DESC")
  end
  
  def new
    @contents = Content.new
  end
  
  def create
    Content.create(content_params)
    redirect_to action: :index
  end
  
  def destroy
    content = Content.find(params[:id])
    content.destroy
    redirect_to action: :index
  end
  
  def edit
  end
  
  def update
    content = Content.find(params[:id])
    content.update(content_params)
    redirect_to action: :index
  end
  
  def show
  end
  
  private
  def content_params
    params.require(:content).permit(:text).merge(user_id: current_user.id)
  end
  
  def set_content
    @contents = Content.find(params[:id])
  end
  
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<p class="text">本文</p>
<%= form_for(@contents, url:{action: 'update'}) do |form| %>
  <%= form.text_area :text, rows: "5" %>
  <%= form.submit "送信" %>
<% end %>

app/views/blog/index.html.erb
<% @blog.each do |blog| %>
  <div class="post-area">
    <p><%= blog.text %></p>
    <div class="sed">
      <p class="show"><%= link_to 'SHOW', blog_path(blog.id), method: :get %></p>
      <% if user_signed_in? && current_user.id == blog.user_id %>
        <p class="edit"><%= link_to 'EDIT', edit_blog_path(blog.id), method: :get %></p>
        <p class="destroy"><%= link_to 'DESTROY', blog_path(blog.id), method: :delete %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/blog/new.html.erb
<p class="text">本文</p>
<%= form_for(@contents, url:{action: 'create'}) do |form| %>
  <%= form.text_area :text, rows: "5" %>
  <%= form.submit "送信" %>
<% end %>

app/views/blog/show.html.erb
<div class="post-area">
  <p><%= @contents.text %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><a href="/">Blog</a></h1>
      <% if user_signed_in? %>
        <div class="option">
          <%= link_to "SignOut", destroy_user_session_path, method: :delete %>
          <%= link_to "New", new_blog_path %>
        </div>
      <% else %>
        <div class="option">
          <%= link_to "SignIn", new_user_session_path %>
          <%= link_to "SignUp", new_user_registration_path %>
        </div>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>